all:
  children:
    redirectors:
      hosts:
        c2-redirector:
          ansible_host: 192.168.90.2
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /root/.ssh/key.pem
    servers:
      hosts:
        c2-server:
          ansible_host: 192.168.1.20
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /root/.ssh/c2.pem


