---
- name: Deploy C2 Redirector
  become: true
  hosts: c2-redirector
  vars_files:
    - vars/ssh_config.yml
  tasks:
    - name: Update repository and upgrade packages
      include_tasks: tasks/update.yml
    - name: Import SSH configuration tasks
      include_tasks: tasks/secure_ssh.yml
    - name: Import Apache installation tasks
      include_tasks: tasks/apache2.yml
  handlers:
    - name: Restart SSH
      service:
        name: ssh
        state: restarted
