---
- name: Deploy C2 Team Server
  become: true
  hosts: c2-teamserver
  vars_files:
    - vars/ssh_config.yml
  tasks:
    - name: Update repository and upgrade packages
      include_tasks: tasks/update.yml
    - name: Configure SSH
      include_tasks: tasks/secure_ssh.yml
    - name: Install and configure Fail2ban
      include_tasks: tasks/fail2ban.yml
    - name: Configure logrotate
      include_tasks: tasks/logrotate.yml
    - name: Set hostname for Team Server
      hostname:
        name: teamserver
  handlers:
    - name: Restart SSH
      service:
        name: ssh
        state: restarted
    - name: Restart Apache2
      service:
        name: apache2
        state: restarted
    - name: Restart fail2ban
      service:
        name: fail2ban
        state: restarted
    - name: Restart rsyslog
      service:
        name: rsyslog
        state: restarted
