- name: Remove existing 000-default.conf symlink
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent
- name: Create symlink for default-ssl.conf
  file:
    src: /etc/apache2/sites-available/default-ssl.conf
    dest: /etc/apache2/sites-enabled/default-ssl.conf
    state: link
  notify: Restart Apache2
    #changed_when: true
