---
- name: Disable root login
  vars:
    sshd_config_file: /etc/ssh/sshd_config
  lineinfile:
    path: "{{ sshd_config_file }}"
    regexp: "^#PermitRootLogin"
    line: "PermitRootLogin no"
    backup: yes
  notify: Restart SSH

- name: Disable SSH Password Authentication
  vars:
    sshd_config_file: /etc/ssh/sshd_config
  lineinfile:
    path: "{{ sshd_config_file }}"
    regexp: "^#PasswordAuthentication"
    line: "PasswordAuthentication no"
    backup: yes
  notify: Restart SSH
